# Generated by Django 5.2.17 on 2026-09-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Estudiante'), ('tutor', 'Tutor'), ('coordinator', 'Coordinador'), ('superadmin', 'Superadministrador'), ('admin', 'Administrador'), ('direccion', 'Direccion'), ('auditor', 'Auditor')], db_index=True, max_length=20, verbose_name='Rol'),
        ),
    ]
